### ISSUE TITLE
REDIRECT with the Name of a new Room and other enhancements

### ISSUE THREAD

**Issue by HPMeyer** [tosterkamp/random-redirect#15]
Thanks a lot for this handy tool.

Perhaps it would be nice, if You can enhance the tool by some features:

1. Supply the Name of a Meeting Room 

   that is, ```jitsi.random-redirect.de/TheRoomWhereWeMeet``` 

   redirects to ```<a_random-jitsi-instance>/TheRoomWhereWeMeet```

   (and  perhaps ```jitsi.random-redirect.de‎?room=TheRoomWhereWeMeet``` should do the same)

2. Select only servers matching an regular expression ```RegEx=<reglar_expression>```, a ```TLD="de"``` or something similar?

 other possibilities (if these informations are somewhere available): 

  ```region=EU```   for the physical location of the resulting servers  

   ```GDPR=true```  

  etc.
  
An Example:
   ```jitsi.random-redirect.de/TheRoomWhereWeMeet?GDPR=true&RegEx="*.freifunk-*.de"``` 

Greetings
HPM in VK

**Comment by tosterkamp** [comment]
This issue is very similar to issue #13. I'll keep the ideas in mind. But I don't have enough time for that right now.
